version: 1.0.0
type: tool
author: sonnguyennam0904
name: claude-think-tool
label:
    en_US: Claude Think Tool
    zh_Hans: Claude 思考工具
description:
    en_US: A tool for Node Agents to perform structured multi-step reasoning, enabling richer context accumulation for better decision-making.
    zh_Hans: 一个供节点代理执行结构化多步推理的工具，能够积累更丰富的上下文以做出更好的决策。
icon: _assets/icon.svg
created_at: 2024-12-01T00:00:00Z
resource:
    type: plugin
    manifest: plugin.yaml
meta:
    tags:
        - reasoning
        - context
        - agent
        - think
plugins:
    tools:
        - provider/think_provider.yaml
